INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('/Film','http://www.slashfilm.com/','Movie news and reviews','Peter Sciretta');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('1000 Awesome Things','http://1000awesomethings.com/','Miscellaneous topics','Neil Pasricha');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('3 Quarks Daily','http://www.3quarksdaily.com/3quarksdaily/','Online news aggregator','S. Abbas Raza');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('A Motley Vision','http://www.motleyvision.org/','Criticism of the Mormon arts, particularly LDS literature and film','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Aangilam','http://www.aangilam.org/','Bilingual education blog','HK Arun');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('AirlineReporter.com','http://www.airlinereporter.com/','Airline industry news','David Parker Brown');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Sports Blog Nation','https://www.sbnation.com/','Sports blog focusing on the Oakland Athletics baseball team','Tyler Bleszinski');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Audimated','http://www.audimated.com/','Music related blog focused on news, resources, and information for independent artists.','Lucas Sommer');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('B2Blogger.com','http://b2blogger.com/','Industrial B2B marketing','Aleksandr Storozhuk');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Bad Astronomy','http://www.slate.com/blogs/bad_astronomy.html','Blog on astronomy and science education','Phil Plait');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Balkinization','https://balkin.blogspot.com/','Blog focusing on US civil liberties issues','Jack Balkin');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Belmont Club','https://pjmedia.com/richardfernandez/','Political and historical blog','Richard Fernandez');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Bestiario del balón','http://bestiariodelbalon.com/','Colombian football blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Blog del Narco','http://www.blogdelnarco.com/','Mexican Drug War','Anonymous');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Blogcritics','http://blogcritics.org/','Multiple sections, mostly involving entertainment and science','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Bloggingheads.tv','https://bloggingheads.tv/','Video blog on politics, philosophy, and science','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Boing Boing','https://boingboing.net/','Politics, science fiction, and general interest','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Borderland Beat','http://www.borderlandbeat.com/','Mexican Drug War','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Brain Blogger','http://brainblogger.com/','Multidimensional biopsychosocial perspectives','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Cake Wrecks','http://www.cakewrecks.com/','Photoblog featuring images of cakes that are humorous or strange in appearance','Jen Yates');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('China Law Blog','http://www.chinalawblog.com/','Blog of news and opinions on Chinese law and business','Dan Harris and Steve Dickinson');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Chinadialogue','https://www.chinadialogue.net/','Blog on the environment, both globally and in China','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Climate Audit','https://climateaudit.org/','Using statistical methods to analyze historical reconstructions of past climates','Stephen McIntyre');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('ConservativeHome','https://www.conservativehome.com/','Conservatism from a UK perspective','Tim Montgomerie');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Consumerist','https://consumerist.com/','Blog on consumerism','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Contempo Magazine','https://issuu.com/contempomagazine','Blog on Hispanic conservatism','Tony Magana');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Core77','http://www.core77.com/','Blog dedicated to the practice and produce of the field of industrial design New York City','Stuart Constantine and Eric Ludlum');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Cosmic Variance','http://blogs.discovermagazine.com/cosmicvariance/','Science blog on physics and astrophysics','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Couric & Co.','https://www.cbsnews.com/evening-news/','Official blog of the CBS Evening News','The CBS Evening Newsstaff');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Crash Test Kitchen','http://www.crashtestkitchen.com/','Cooking and food video blog','Waz and Lenny (screen names)');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Crooked Timber','http://crookedtimber.org/','Various intellectual topics, such as: Left-of-center politics, economics, sociology, and modern literature','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Crooks and Liars','http://crooksandliars.com/','Liberal video blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Cute Overload','http://cuteoverload.com/','Photos and videos of "cute" animals','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Daring Fireball','https://daringfireball.net/','Macintosh and technology blog','John Gruber');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Deadspin','http://deadspin.com/','Sports blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('DesiPundit','http://www.desipundit.com/','Commentary on India''s major blog posts','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Diabetes Mine','http://www.healthline.com/diabetesmine','Blog relating to diabetes','Amy Tenderich');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Dlisted','http://dlisted.com/','Celebrity gossip','Michael K.');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Down By The Hipster','http://www.downbythehipster.com/','Blog on the New York City nightlife','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('DrugWarRant','http://www.drugwarrant.com/','Blog used to advocate the termination of the War on Drugs in the United States','Peter Guither');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('EastSouthWestNorth','http://www.zonaeuropa.com/weblog.htm','China focused blog out of Hong Kong','Roland Soong');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Engadget','https://www.engadget.com/','Technology blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('EQ Music','https://eqmusicblog.com/#','Electronic pop music blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Faces in Places','http://facesinplaces.blogspot.com/','Photo blog of faces seen in everyday objects','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Fluxblog','http://www.fluxblog.org/','MP3 blog','Matthew Perpetua');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('FoodMayhem','http://foodmayhem.com/','Blog about all topics related to food','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Front Porch Republic','http://www.frontporchrepublic.com/','Localist blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Gawker','http://gawker.com/','Manhattan news and gossip','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('GeenStijl','https://www.geenstijl.nl/','General commentary','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Generación invisible','http://generacioninvisible.blogspot.com/','Blog by professional journalists','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Gigaom','https://gigaom.com/','Blog with opinions on startups, new technologies, broadband, and online games','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Gizmodo','http://gizmodo.com/','Consumer electronics centered blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Go Fug Yourself','https://www.gofugyourself.com/','Comedy fashion blog','Jessica Morgan and Heather Cocks');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Google Blogoscoped','http://blogoscoped.com/','Blog covering the Google search engine','Philip Lenssen');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Gothamist','http://www.gothamistllc.com/','Local interest blog about New York, branch sites cover other cities','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Groklaw','http://www.groklaw.net/','Blog covering legal news pertinent to a free and open-source software community','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Grumpy Old Bookman','http://grumpyoldbookman.blogspot.com/','Litblog','Michael Allen');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Gulfsails','http://gulfsails.blogspot.com/','Documented the effects of Hurricane Katrina in New Orleans','Troy Gilbert');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Hollaback!','https://www.ihollaback.org/','Photoblog intended to raise awareness of street harassment','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Hot Air','https://hotair.com/','Center-right political and news blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('How the World Sees America','http://newsweek.washingtonpost.com/postglobal/america/','Blog showcasing views on the United States from around the world','Amar C. Bakshi');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('I Can Has Cheezburger?','http://icanhas.cheezburger.com/','Blog featuring lolcats and other animals created by the writers','Eric Nakagawa and Kari Unebasami');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Idolblog','http://www.idolblog.com/','Blog dedicated to the talent search show New Zealand Idol','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('India Uncut','http://indiauncut.com/','blog regarding India','Amit Varma');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Inhabitat','http://inhabitat.com/','Blog on sustainable architecture','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('InkTank','https://beardedcoffeemonkey.com/','Blog on webcomics','Barry Smith');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('IPKat','http://ipkitten.blogspot.com/','Blog dedicated to intellectual property law','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('IvyGate','https://www.ivygateblog.com/','News and gossip from Ivy League schools','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Jezebel','http://jezebel.com/','Women''s interest blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Jihad Watch','https://www.jihadwatch.org/','Blog on the ideas behind Islamic jihad','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Joystiq','https://web.archive.org/web/20090725090005/http://www.joystiq.com//2009//07//09//battlefield-1943-servers-being-added-around-the-clock//','Video gaming blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Kaboom: A Soldier''s War Journal','http://kaboomwarjournalarchive.blogspot.com/','Military blog detailing a scout platoon leader''s daily life on the Iraqi frontlines','LT G. (screen name)');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Kotaku','http://kotaku.com/','Video game blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Language Log','http://languagelog.ldc.upenn.edu/nll/','Language blog','Mark Liberman');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Law and the Multiverse','http://lawandthemultiverse.com/','Law and comic books blog','James Daily and Ryan Davidson');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Lebanese Political Journal','https://en.wikipedia.org/wiki/Lebanese_Political_Journal','Blog commenting on various aspects of Lebanese politics','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Liberty and Power','http://historynewsnetwork.org/blog/author/32','A Libertarian political blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Lifehacker','http://lifehacker.com/','Blog covering life hacks','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Little Green Footballs','http://littlegreenfootballs.com/','Center-left political blog','Charles Foster Johnson');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Marginal Revolution','http://marginalrevolution.com/','Economics focused blog','Tyler Cowen and Alex Tabarrok');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Mashable','http://mashable.com/','Social networking news based blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Memepool','http://meme-pool.tumblr.com/','Link blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('MetaFilter','http://www.metafilter.com/','Link and general interest blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Metro Jacksonville','http://www.metrojacksonville.com/','Urban development news and discussion blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Milblogging.com','https://milblogging.com/','Blog index to other military blogs','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Mind Hacks','https://mindhacks.com/','Psychology and neuroscience blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Mini-Microsoft','http://minimsft.blogspot.com/','Blog on Microsoft','Anonymous');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Momversation','http://www.momversation.com/','Home and family blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Monsters and Critics','http://www.monstersandcritics.com/','News blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Mr. Money Mustache','http://www.mrmoneymustache.com/','Personal Finance blog','Peter Adeney');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('MSDN Blogs','https://developer.microsoft.com/en-us/','Microsoft blog where employees blog to a public audience','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('MyDD','http://www.mydd.com/','Progressive American politics blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Node Magazine','https://nodemagazine.wordpress.com/','Blog to annotate the novel Spook Country','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('OpEdNews','https://www.opednews.com/','Blog on U.S. and world political issues','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Overheard in New York','https://overheardinnewyork.com/','Humor blog of conversations heard in New York','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Overheard in Pittsburgh','https://overheardeverywhere.com/archives/category/overheard-in-pittsburgh/','Humor blog of conversations heard in Pittsburgh','Chris Griswold');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Patentlyo','https://patentlyo.com/','Patent law blog','Dennis Crouch');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Patribotics','https://patribotics.blog/','Political investigative journalism','Louise Mensch');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Pharyngula','https://freethoughtblogs.com/pharyngula/','Science blog','PZ Myers');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Politically Incorrect','http://www.pi-news.org/','Political blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Popjustice','https://www.popjustice.com/','Music blog','Peter Robinson');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('PopSugar','https://corp.popsugar.com/','Gossip and celebrity news blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('PopText','http://poptext.blogspot.com/','Mp3 Blog','Abigail McDonald');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('ProBlogger.com','https://problogger.com/','Blog tips','Darren Rowse');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Protein Wisdom','http://proteinwisdom.com/','Conservative and Libertarian political blog','Jeff Goldstein');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Rate Your Students','http://rateyourstudents.blogspot.com/','Parody blog on the behavior of college students','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('ReadWrite','https://readwrite.com/','Blog on web technology','Richard MacManus');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('RealClimate','http://www.realclimate.org/','Blog on climatology','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Retecool','http://www.retecool.com/','Shocklog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Rocketboom','http://www.rocketboom.com/','Video blog','Andrew Baron and Joanne Colan');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('SCOTUSblog','http://www.scotusblog.com/','Blog on the Supreme Court of the United States','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Seeking Alpha','https://seekingalpha.com/','Provides free stock market advice through a blog format','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Sense on Cents','http://www.senseoncents.com/','Provides information on financial markets and the economy','Larry Doyle');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Simply Recipes','http://www.simplyrecipes.com/','Cooking recipes','Elise Bauer');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Skatter Tech','https://skatter.com/','Technology review blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Slugger O''Toole','https://sluggerotoole.com/','Irish news blog','Mick Fealty');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Smashing Magazine','https://www.smashingmagazine.com/','Blog on web design and web development','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Squawk Box','https://www.cnbc.com/squawk-box-us/','Blog for the CNBC show Squawk Box','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Stuff White People Like','https://stuffwhitepeoplelike.com/','Satirical blog about the interests of upper class white Americans','Christian Lander');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Surviving Grady','http://www.survivinggrady.com','Boston Red Sox blog','Red and Denton (screen names)');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('TechCrunch','https://techcrunch.com/','Blog covering Web 2.0 products and companies','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Terra Nova','http://terranova.blogs.com/terra_nova/','Blog related to game studies and virtual worlds','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The "Blog" of "Unnecessary" Quotation Marks','http://www.unnecessaryquotes.com/','Blog about the misuse of English quotation marks','Bethany Keeley');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Art Life','http://theartlife.com.au/','Blog about the art scene in Sydney, Australia','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Bear Club','https://thebearclub.wordpress.com/','Niche blogging site for teddy bears and their collectors','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Blonde Salad','http://www.chiaraferragnicollection.com/us_en','Fashion','Chiara Ferragni');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Brussels Journal','https://www.brusselsjournal.com/','Conservative blog on Belgian politics','Paul Beli n');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Comics Curmudgeon','https://joshreads.com/','Critical analysis of newspaper comics','Josh Fruhlinger');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Daily Howler','http://dailyhowler.blogspot.com/','Center-left political blog','Bob Somerby');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Daily Nightly','http://dailynightly.msnbc.com/archives.html','Official blog of NBC Nightly News','Brian Williams and other NBC Newscorrespondents');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Huffington Post','http://www.huffingtonpost.com/','Liberal news blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Incidental Economist','http://theincidentaleconomist.com/','Blog focused on economics, health policy, law','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Marmot''s Hole','http://marmotshole.blogspot.com/','Blog focusing on Korean politics and society','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Oil Drum','http://www.theoildrum.com/','Blog on energy issues','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Panda''s Thumb','https://pandasthumb.org/','Blog on the creation-evolution controversy','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Sartorialist','http://www.thesartorialist.com/','Fashion blog','Scott Schuman');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Scientific Activist','http://scienceblogs.com/scientificactivist/','Blog on science, politics, and science policy','Nick Anthis');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('the show with zefrank','http://www.zefrank.com/','Comedy and current events video blog','Ze Frank');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Sneeze','http://thesneeze.com/','General interest blog','Steve (screen name)');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Soxaholix','http://www.soxaholix.com/','Comic-based blog for discussing the Boston Red Sox','Hart Brachen');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Tehran Times','http://thetehrantimes.tumblr.com/','Blog related to Iranian street fashion','Araz Fazaeli');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Underwear Expert','http://www.underwearexpert.com/','Men''s underwear blog','Michael Kleinmann');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('The Volokh Conspiracy','https://www.washingtonpost.com/news/volokh-conspiracy/?utm_term=.a6851eb06d92','Conservative political blog written mainly by law professors','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('TorrentFreak','https://torrentfreak.com/','BitTorrent news blog','Ernesto (screen name)');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('TPMCafe','http://talkingpointsmemo.com/cafe','Center-left political blog portal','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('TrueHoop','http://www.espn.com/blog/truehoop','Blog on basketball, primarily the NBA','Henry Abbott');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('TV Newser','http://www.adweek.com/tvnewser/','American television news ticker blog','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Valleywag','http://valleywag.gawker.com/','Gossip and news on Silicon Valley personalities','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Velvet Underground','https://velvetunderground.co.il/','Israeli news blog','Dvorit Shargal');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Vlogbrothers','https://www.youtube.com/user/vlogbrothers','Multi-topic video blog which generally focuses on science, literature, pop culture, nerd culture, etc. The Green Brothers created a popular online community known as Nerdfighteria (Members of which are called Nerdfighters).','Hank Green and John Green');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Watts Up With That?','https://wattsupwiththat.com/','Blog on man made global warming','Anthony Watts');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Wise Bread','http://www.wisebread.com/','Blog on personal finances','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Yummly','https://www.yummly.com/','Blog on food, recipes, and technology','Multi-author');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Zen Habits','https://zenhabits.net/','Blog on productivity, Getting Things Done, simplifying, living frugal, happiness, and related topics.','Leo Babauta');
INSERT INTO blog_reviews_db.blogs(title,website,description,blog_author) VALUES ('Zooillogix','http://scienceblogs.com/zooillogix/','Blog on zoology','Andrew and Benny Bleiman');


INSERT INTO blog_reviews_db.users (name) VALUES ("Abby"), ("Brittany"), ("Clyde");


INSERT INTO blog_reviews_db.reviews (title, body, rating, BlogId, UserId) 
VALUES 
("Best blog ever!!", "I love this blog. It's so good. Literally nothing I've read has ever been so good.", 5, 1, 1),
("Worst blog ever!!", "I hate this blog. It sucks. I'd rather have shards of glass in my eyes than read another word.", 1, 2, 1),
("It's okay...", "Mediocre blog. Not really worth the time it took to read.", 3, 1, 2);